version: '3'
services:
  web:
    image: cyberbull/cyberbull-web
    build:
      context: .
      args:
        - JAR_FILE: build/libs/\*.jar
    ports:
      - 8080:8080
    container_name: webby
    env_file:
      - .env
  db:
    image: couchbase
    ports:
      - 8091:8091
      - 8093:8093
    expose:
      - 8091
      - 8092
      - 8093
    container_name: couchie
    # volumes:
    #   - ./data:/opt/couchbase/var/lib/couchbase/data