spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testuser5626@gmail.com
    password: 4Us6F3pzUBCf2tA#b@d@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000